### ISSUE TITLE
strawberryperl.com is gone / doesn't resolve

### ISSUE THREAD

**Issue by mauke** [StrawberryPerl/strawberryperl.com#10]
$ ping -c1 strawberryperl.com                                                    
    ping: strawberryperl.com: Name or service not known

Also:

> Server not found
> Firefox can’t find the server at www.strawberryperl.com.

**Comment by adamkennedy** [comment]
Resolved.

The hosting company was blacklisted by the cpan.org mail servers so I
didn't get any notices.

Adam
