### ISSUE TITLE
Website is not working

### ISSUE THREAD

**Issue by pplu** [StrawberryPerl/strawberryperl.com#14]
The main website: www.strawberryperl.com is not working. It seems like the nameservers are not resolving addresses for strawberrperl.com.

@kmx @chorny @frioux @xdg : I don't know who the owner is, but since you are members of the StrawberryPerl organization, I figured you could maybe have the solution in your hands.

**Comment by frioux** [comment]
CC'ing owner

On Mon, Jul 30, 2018 at 08:08:50AM -0700, Jose Luis Martinez wrote:
> The main website: www.strawberryperl.com is not working. It seems like the nameservers are not resolving addresses for strawberrperl.com.
> 
> @kmx @chorny @frioux @xdg : I don't know who the owner is, but since you are members of the StrawberryPerl organization, I figured you could maybe have the solution in your hands.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/StrawberryPerl/strawberryperl.com/issues/14

-- 
fREW Schmidt
https://blog.afoolishmanifesto.com

**Comment by aligature** [comment]
Looks to be back up now.
