### ISSUE TITLE
strawberryperl.com dns issue

### ISSUE THREAD

**Issue by mcgoo** [StrawberryPerl/strawberryperl.com#16]
```
C:\>ping www.strawberryperl.com
Ping request could not find host www.strawberryperl.com. Please check the name and try again.

C:\>ping strawberryperl.com
Ping request could not find host strawberryperl.com. Please check the name and try again.
```
Seems similar to :- https://github.com/StrawberryPerl/strawberryperl.com/issues/10

(The upshot being that I can't hit the website or download the package.)

**Comment by kmx** [comment]
Thanks for your report.

ping @adamkennedy

**Comment by rivy** [comment]
Same issue here...

After having a couple of non-connections over the last couple of days, the domain completely stopped resolving between 6 and 12 hours ago (my AppVeyor CI builds stopped working about that time).

**Comment by rivy** [comment]
@kmx , are there any mirrors?

**Comment by kmx** [comment]
> @kmx , are there any mirrors?

unfortunately no

**Comment by MoritzMaxeiner** [comment]
Is only the domain not resolving or is the server also down? If it's only not resolving, people could temporarily hack around the issue by adding the server's IPv4/IPV6 address(es) to their local resolvers.

**Comment by rivy** [comment]
I've setup a repository on github that can act as a backup mirror ([rivy/CI.AppVeyor.helpers-perl-binaries](https://github.com/rivy/CI.AppVeyor.helpers-perl-binaries)). But I'm missing a few of the commonly used binaries:

- strawberry-perl-5.14.4.1-64bit.zip
- strawberry-perl-5.16.3.1-64bit.zip
- strawberry-perl-5.26.1.1-64bit.zip
- strawberry-perl-5.28.0.1-64bit.zip

@kmx , do you have copies of these stashed somewhere that I could obtain and post?

**Comment by rivy** [comment]
... and ... the site just came back up.

**Comment by simcop2387** [comment]
I've started mirroring it at https://strawberry.perl.bot/ it's not automated yet but I'll do my best to keep it up to date.

**Comment by rivy** [comment]
I've also made available a baseline set of Perl binaries as release assets at <https://github.com/rivy/CI.AppVeyor.helpers-perl-binaries/releases>.

They'll remain up as backup assets for AppVeyor CI builds during any future outages.

**Comment by uilianries** [comment]
> 
> 
> ```
> C:\>ping www.strawberryperl.com
> Ping request could not find host www.strawberryperl.com. Please check the name and try again.
> 
> C:\>ping strawberryperl.com
> Ping request could not find host strawberryperl.com. Please check the name and try again.
> ```
> 
> Seems similar to :- #10
> 
> (The upshot being that I can't hit the website or download the package.)

Same error for me today.

**Comment by simcop2387** [comment]
Haven't seen it down myself, seems to be working right now.  Some intermittent issue?

**Comment by uilianries** [comment]
I think is my DNS. According https://downforeveryoneorjustme.com/strawberryperl.com

Regards!
