### ISSUE TITLE
5.30.0.1 zip installer for windows (32 and 64 bit) is always stuck at 121MB.

### ISSUE THREAD

**Issue by acdemiralp** [StrawberryPerl/strawberryperl.com#17]
It downloads fine until 121MB and then stops. This breaks all vcpkg packages depending on it.

**Comment by kmx** [comment]
Please post the exact URL

**Comment by acdemiralp** [comment]
Hello,

It was http://strawberryperl.com/download/5.30.1.1/strawberry-perl-5.30.1.1-32bit.zip but I just downloaded from home and everything is fine. Perhaps eduroam / university firewall was blocking it.

We may close the issue since it doesn't exist.

**Comment by kmx** [comment]
great, thanks for your time
