### ISSUE TITLE
Corporate firewall blocks downloads

### ISSUE THREAD

**Issue by kenr** [StrawberryPerl/strawberryperl.com#18]
From inside our corporate firewall we are not able to download the .zip files.
The reason is that the firewall identifies .bat files as threats. It seems the redirects contains .bat in their filname.

Here are the "files" the firewall blocks:
portableshell.bat
relocation.pl.bat

I guess this is not related to the code in this repo, but more to the setup of the site that runs this code?

**Comment by kmx** [comment]
Should be better now when the site uses https.
