### ISSUE TITLE
Website fails to disclose licensing information and/or redistribution rules/agreements

### ISSUE THREAD

**Issue by gitcnd** [StrawberryPerl/strawberryperl.com#22]
I'm pretty sure you're supposed to give people a clue about license agreements before they download?

It would be very useful to tell us about re-distribution rules - can we ship our perl products on windows and auto-deliver StrawberryPerl with it?  What, if any, rules apply to that?

NB: That's a rhetorical question - you should tell us before we have to ask...

**Comment by kmx** [comment]
Licence info is in c:\strawberry\licenses\*

As it is dynamically generated (based on packages/libraries included) it is always good to check particular ZIP / MSI content as they may vary.
