### ISSUE TITLE
Slow download speed of any file

### ISSUE THREAD

**Issue by AenBleidd** [StrawberryPerl/strawberryperl.com#23]
Hello,

I use vcpkg to install OpenSSL on Windows and one o the dependencies is Strawberry Perl.
But for several days now I have a very slow download speed from http://strawberryperl.com/ (e.g. http://strawberryperl.com/download/5.30.2.1/strawberry-perl-5.30.2.1-32bit.zip) and it takes me more than an hour to download this particular file

Could you please resolve this issue?

**Comment by kmx** [comment]
@adamkennedy could you please review the setting/configuration of DreamHost hosting where AFAIK only you have an access.

It is not only a problem for people who wants to downaload strawberry perl but also for me wanting to upload new release (I am currently uploading 16KB/s which is a bit demotivating).

Mark (@shadowcat-mdk), would it be possible make some kind of agreement between EPO and @adamkennedy and put the strawberryperl.com domain and hosting under control of EPO as the long term sponsor of strawberry perl?

**Comment by shogo82148** [comment]
ping.
I'm looking forward new binary of Perl 5.32.0, but it looks that this issue blocks the release.

**Comment by kmx** [comment]
@shogo82148 
* http://strawberryperl.com/download/5.32.0.1/strawberry-perl-5.32.0.1-64bit.msi
* http://strawberryperl.com/download/5.32.0.1/strawberry-perl-5.32.0.1-32bit.msi

**Comment by shogo82148** [comment]
@kmx Thanks!

**Comment by kmx** [comment]
Tested now on https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-64bit.msi - it took approx. 20 sec.

**Comment by dennisameling** [comment]
@kmx This issue still seems to be present unfortunately. It takes around 10 mins to download Strawberry Perl from your server - I'm based in The Netherlands (IP starts with 37.203.63.XXX). Am on a symmetrical optic fiber connection (200/200Mbps) and downloads from other servers work flawlessly. Getting only 1.5-2Mbps when downloading Strawberry Perl. Any chance this could be improved somehow? Thanks very much in advance!

```
Elapsed time for package libiconv:x64-windows: 2.968 min

Total elapsed time: 3.003 min

    Finished libiconv
    Installing package openssl...
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x64-windows -> 1.1.1k#6
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Dennis\AppData\Local\vcpkg\archives\2e\2ed504dc3c54e24f17d059d48912670c610560fe5a0e5868a88c9480d788320f.zip
Starting package 1/1: openssl:x64-windows
Building package openssl[core]:x64-windows...
-- Downloading https://www.openssl.org/source/openssl-1.1.1k.tar.gz;https://www.openssl.org/source/old/1.1.1/openssl-1.1.1k.tar.gz -> openssl-1.1.1k.tar.gz...
-- Downloading https://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip -> strawberry-perl-5.30.0.1-32bit.zip...
```

**Comment by shogo82148** [comment]
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/21 was closed, however cloud you rethink it again?

- https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/21

some projects upload their binaries into GitHub releases.

- https://github.com/ruby/ruby-builder/releases/tag/toolcache
  - each binaries are ~20MB and ~500 binaries are here.
  - totally ~10GB
- https://github.com/actions/go-versions
  - each binaries are ~100MB and ~200 binaries are here.
  - totally ~20GB

Or recently, [GitHub Packages Container registry is generally available](https://github.blog/2021-06-21-github-packages-container-registry-generally-available/)

> Homebrew now hosts all of their bottles on the Container registry. This was made possible because the Container registry supports OCI images. Homebrew can now distribute over a half a petabyte of binary packages to their users every month while surfacing them in GitHub search for improved discoverability

Homebrew now distributes over a half a petabyte of binary packages using it.

For these reasons, I think GitHub can now adequately provide a 54GB mirror.

**Comment by BA7LYA** [comment]
I use vcpkg in my dev-env, and It took me 1 hour and 5 minutes to download Strawberry Perl 5.32.1.1 32bit, it's really agonising, is there anyone have some good idea about how to deal with this? I really need some help.

**Comment by snzmnrdn** [comment]
Hi, btw i got the way to solve it using dirty method.

Requirement using chocolatey (https://chocolatey.org/install#install-step2) `PowerShell` 👍
```
choco install mkcert
choco install nginx
```

**First step:**
```
mkcert -install
mkcert strawberryperl.com localhost 127.0.0.1 ::1
```
the ssl file generated on path that you run the command `strawberryperl.com+3.pem` `strawberryperl.com+3-key.pem`

**Second step:**
Modify the nginx config in `C:/tools/nginx-1.****/conf/nginx.conf`

*from*
```
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }
 ```
 
*to*
 
 ```
        listen 443 ssl;  # Listen on HTTPS port
        server_name strawberryperl.com;  # Your domain name

        ssl_certificate C:\Users\YOURUSERNAME\strawberryperl.com+3.pem;
        ssl_certificate_key C:\Users\YOURUSERNAME\strawberryperl.com+3-key.pem;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        # listen       80;
        # server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }
```

after that run `services.msc` look for nginx service and restart

**Third step:**
Modify host at `C:\Windows\System32\drivers\etc\hosts`

```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
#      102.54.94.97     rhino.acme.com          # source server
#       38.25.63.10     x.acme.com              # x client host

# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost
127.0.0.1   strawberryperl.com
```

**Final step:**
Create directory in `C:/tools/nginx-1.****/html`
```
html
   download
     5.32.1.1
```
`e.g. C:\tools\nginx-1.25.1\html\download\5.32.1.1` and paste this zip file 
`*version that i have for now`
[strawberry-perl-5.30.0.1-32bit.zip](http://124.217.254.110/files/strawberry-perl-5.30.0.1-32bit.zip)
[strawberry-perl-5.32.1.1-32bit.zip](http://124.217.254.110/files/strawberry-perl-5.32.1.1-32bit.zip)

You can directly download https://strawberryperl.com/download/VERSION/strawberry-perl-VERSION-32bit.zip (it host on your machine)

`P/S - i need to get that file fast download in AWS EC2 instance, using my own isp at home really2 slow. Not sure the issue on DNS or internet routing`

**Comment by adamkennedy** [comment]
@kmx et al. I'm not sure the Dreamhost account is/was really suitable for high bandwidth downloading like this, and it sounds like it's become an increasing problem. I don't have an objection to distributing/mirroring the files via GitHub releases or some other mechanism.

**Comment by genio** [comment]
@adamkennedy I've been trying for quite some time to get access to the sp site so we can make updates and push releases. I'll be happy to take over cost and maintenance/whatever necessary so we can continue working towards the goal of keeping sp releases going. We are stuck right now.
