### ISSUE TITLE
Request: A docker image for strawberry perl (windows/PS)

### ISSUE THREAD

**Issue by PaulGWebster** [StrawberryPerl/strawberryperl.com#24]
Good day all, I was just wondering if 5.32.0 was released yet for Strawberry perl, as the time of writing it is not ... so I had a look into howto build a windows binary (thank you for all the work on making that easier!) but still quite a task!

So then I wondered if it would be possible to make a docker for the build process, so it would be simple to load whichever perl you wanted into say c:\buildsrc\<src tarbell> and have all the tools automatically build it, I thought the idea would be such a good one I wrote this request tracker :)

So yes if anyone has any ideas if this would not work or so, or I could help out create it please post in thread, can certainly give it a try!

**Comment by kmx** [comment]
Current build process must run on a MS Windows machine. I am not sure if it is even possible to put it into a container.

**Comment by shawnlaffan** [comment]
The build system is now set up to use docker.  See https://github.com/StrawberryPerl/spbuild

@genio - I think this issue can be closed (I don't seem to have permissions for this repo).

**Comment by genio** [comment]
Sorry about that. You should have permissions now.
