### ISSUE TITLE
Website fails to disclose licensing information and/or redistribution rules/agreements

### ISSUE THREAD

**Issue by gitcnd** [StrawberryPerl/strawberryperl.com#25]
This is a dupe of the same topic that just got closed without being fixed.

Put the license ON THE WEB SITE - it needs to be readable BEFORE you install/download, not in some hidden file afterwards.

Some people care about this stuff, if that's not you - leave this issue alone and lets someone who does care fix it properly.

**Comment by kmx** [comment]
duplicate #22
