### ISSUE TITLE
perl 5.34 has been released, when can I download it?

### ISSUE THREAD

**Issue by fenginsc** [StrawberryPerl/strawberryperl.com#26]
The release does not seem to be very timely, is it currently built manually? Are there any plans to build it automatically? For example, use the current mainstream CI/CD tools.

**Comment by choroba** [comment]
New maintainers are working on it, but their unfamiliarity with the ecosystem is slowing them down. Be patient.

**Comment by fenginsc** [comment]
> New maintainers are working on it, but their unfamiliarity with the ecosystem is slowing them down. Be patient.

You are right, i just want to know what happened, thanks.

**Comment by xavier2k6** [comment]
`5.34.1` is out now.

Are the new maintainers making headway with the ecosystem?

**Comment by niceperl** [comment]
And now we have the 5.36 release waiting for Windows support ...

**Comment by sisyphus** [comment]
Note that perl-5.34.0, perl-5.34.1 and perl-5.36.0 all build straight out
of the box using mingw-w64 compilers, so long as the mingw-w64 compiler
being used has mingw runtime version 8 or earlier.
(The mingw runtime version of the gcc-8.3.0 that ships with
StrawberryPerl-5.32.x uses mingw runtime version 6.)
It also builds straight out of the box with Visual Studio compilers.

Of course, the main attraction  of Strawberry Perl is not that it provides
a build of perl for windows, but that it additionally provides a large
number of 3rd party C libraries, and a large number of non-core modules (in
vendor/lib).

Cheers,
Rob

**Comment by niceperl** [comment]
Nice to know, but I think the strawberry strong point is that you don't have to build Perl. 
Now I'm using WSL 2 with a Linux container, and perlbrew with the Perl I need.

**Comment by genio** [comment]
While it's true that Strawberry will compile with MinGW, it's not as simple as it sounds. https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/28#issuecomment-1127684898 and https://github.com/StrawberryPerl/spbuild can help explain the process a bit

**Comment by sisyphus** [comment]
On Tue, May 31, 2022 at 10:52 PM Chase Whitener ***@***.***>
wrote:

> While it's true that Strawberry will compile with MinGW, it's not as
> simple as it sounds.
>
I actually disagree with that.
Building perl is incredibly easy - though, admittedly, everything is easy
when you know how ;-)
If you've got StrawberryPerl-5.32.x, then you've got everything you need to
build perl-5.34.x and perl-5.36.x.
Just tell me the location where you want to install your perl, the location
of the gcc.exe that is going to build that perl, and whether that gcc.exe
is 32-bit or 64-bit, and I'll provide the 2 commands that need to be run
(in the windows cmd.exe shell) in order to build and install that perl,
with the same configuration as StrawberryPerl provides.
(The second command of those 2 commands is simply "gmake install").

> StrawberryPerl/Perl-Dist-Strawberry#28 (comment)
> <https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/28#issuecomment-1127684898>
> and https://github.com/StrawberryPerl/spbuild can help explain the
> process a bit
>
Neither of those links are relevant to the building of perl itself - though
they are very relevant  to the building of those extras that ship with
StrawberryPerl.

Cheers,
Rob

**Comment by genio** [comment]
All of that surrounding stuff _is_ building Strawberry Perl. Getting the environment setup correctly to build a release is part of the build. Building the various libraries on the actual version of MinGW we're using _is_ building Strawberry.

I think we're mixing up being able to compile Perl vs making an actual Strawberry release.

**Comment by sisyphus** [comment]
On Wed, Jun 1, 2022 at 12:38 AM Chase Whitener ***@***.***>
wrote:

> I think we're mixing up being able to compile Perl vs making an actual
> Strawberry release.
>
Yes, I think so.

I just wanted Miguel to know that if it's just a matter of compiling
perl-5.36.0 from source, then it's really a very simple task.
But if you're wanting any of the additional  stuff that StrawberryPerl
provides then, as you've indicated, the work increases - in amount and
complexity.

Cheers,
Rob

**Comment by fenginsc** [comment]
In my opinion Strawberry Perl is the best out-of-the-box perl environment for the windows platform. I'll continue to wait for the new version to be released, but I wonder if the current Strawberry Perl is not releasing a new version because there are some intractable problems? As you can see the latest version 5.36 has also been released.

**Comment by genio** [comment]
@fenginsc I haven't gotten 5.34 or 5.36 released yet because I've just taken on the project and there are tons and tons of things to get exactly right. I provided links above that describe some of the complexities. It's being worked on.

**Comment by matthewpersico** [comment]
What can I do to help?

**Comment by shawnlaffan** [comment]
A development release of 5.36.1 built using gcc-13.1 is available at https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/dev_5361_20230506_gcc13

We'll circle back to 5.34 once 5.36 is out (and maybe also 5.38 given it is imminent).

Please test it and log any issues on the [Perl-Dist-Strawberry issue tracker](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues).
 
The list of known issues is at https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues?q=is%3Aissue+is%3Aopen+label%3Aperl5.36


@matthewpersico - is the offer of help still open?

**Comment by fenginsc** [comment]
Great, very much looking forward to the official arrival of the new version.

**Comment by matthewpersico** [comment]
> @matthewpersico - is the offer of help still open?

Significant changes in my life since June 2022, but if you have a task list, let me see it and I'll try to pick items off.

**Comment by shawnlaffan** [comment]
Thanks @matthewpersico 

The current list of issues is at https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues?q=is%3Aissue+is%3Aopen+label%3Aperl5.36

The main issue is with PDL, which is segfaulting.  This might be deeper than you want to get into but maybe something with the build env will stand out.  

The current patches and config settings are at https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/25410d3e11085fec4549b3ddfbdda2b565aa2615/share/64bit-5.36.1.1.pp#L54-L82.

**Comment by shawnlaffan** [comment]
Strawberry Perl 5.36.1.1 and 5.38.0.1 have been released.  

The website is a work in progress as we don't yet have access. In the meantime they can be downloaded from https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/SP_5380_5361

A SP 5.34 might be built for completeness.  That's being tracked in https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/124

I'll close this issue in a few days (maybe a bit later) unless there is a reason to keep it open.

**Comment by fenginsc** [comment]
@shawnlaffan 
Awesome, thank you so much for your work, I can't wait to start downloading the latest version now.
In the meantime, I think releasing version 5.34 is necessary because not all of us will be using the latest version, and finally, good luck with your 5.34 release.

**Comment by shawnlaffan** [comment]
Closing issue as promised, albeit somewhat later than initially thought.
