### ISSUE TITLE
strawberryperl.com still lists most recent version as 5.32.

### ISSUE THREAD

**Issue by tobyink** [StrawberryPerl/strawberryperl.com#28]
Is this really the latest build?

Is Strawberry Perl dead?

**Comment by sisyphus** [comment]
@genio is working on releases for 5.34 and 5.36.
It was always going to be "interesting" to see what happened when @kmx (the previous maintainer) decided to quit.
I think that a big part of the problem has been that the "succession" plan (if such a thing even existed) was not as straightforward as one would like.
@genio is, in addition to picking up the pieces, also working on making it easier for such future "successions" to happen.

There's some further discussion about progress on this at #26 and https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/39 .

Cheers,
Rob

**Comment by tobyink** [comment]
That's good news.

**Comment by genio** [comment]
Gonna close this out as it's being worked on and I've been able to rope a few people into helping as well.
