### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by Rand-Random** [StrawberryPerl/strawberryperl.com#29]
Download speed is really bad
![image](https://user-images.githubusercontent.com/9868626/196762283-219887c0-2d02-439a-8e71-a3268aa38aa4.png)

**Comment by ba7lya** [comment]
@Rand-Random same for me, even worse, 2k/sec, really bad.

**Comment by shawnlaffan** [comment]
The latest versions are available via github.  See https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/

Updating the website itself is still a work in progress.  See https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/114

Unless there is a reason to keep it open I will close this issue in a few days, or when I next do a sweep of the issues in this repo
